/**
 * ============================================================================
 * Centralized Backend Security Module - Validation Rules
 * ============================================================================
 * Responsibility: Single source of truth for configurable input limits,
 * required constraints, regex patterns, and security flags across the system.
 */

import { RuleDefinition } from "./securityTypes";

export const VALIDATION_RULES: Record<string, RuleDefinition> = {
  CONTACT_NAME: {
    fieldName: "Contact Name",
    minLength: 2,
    maxLength: 26,
    required: true,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 10,
  },
  INQUIRER_NAME: {
    fieldName: "Inquirer Full Name",
    minLength: 2,
    maxLength: 26,
    required: true,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 10,
  },
  CHAT_LABEL: {
    fieldName: "Chat Label Name",
    minLength: 1,
    maxLength: 80,
    required: true,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 10,
  },
  FEEDBACK: {
    fieldName: "Feedback",
    minLength: 5,
    maxLength: 2000,
    required: false,
    normalizeWhitespace: true,
    keepNewlines: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 15,
  },
  CONTACT_MESSAGE: {
    fieldName: "Contact Message",
    minLength: 5,
    maxLength: 3000,
    required: true,
    normalizeWhitespace: true,
    keepNewlines: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 15,
  },
  MESSAGE: {
    fieldName: "Message",
    minLength: 1,
    maxLength: 10000,
    required: true,
    normalizeWhitespace: false,
    keepNewlines: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 50,
  },
  SEARCH: {
    fieldName: "Search Field",
    minLength: 0,
    maxLength: 200,
    required: false,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 10,
  },
  EMAIL: {
    fieldName: "Email Address",
    minLength: 3,
    maxLength: 254,
    required: true,
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
  },
  PHONE: {
    fieldName: "Phone Number",
    minLength: 10,
    maxLength: 15,
    required: true,
    pattern: /^\+?[0-9\s\-()]{10,15}$/,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
  },
  USERNAME: {
    fieldName: "Username",
    minLength: 3,
    maxLength: 50,
    required: true,
    pattern: /^[a-zA-Z0-9_\-\. ]{3,50}$/,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 10,
  },
  CHAT_ID: {
    fieldName: "Chat ID",
    minLength: 1,
    maxLength: 128,
    required: true,
    pattern: /^[a-zA-Z0-9_\-]+$/,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
  },
  GENERIC_TEXT: {
    fieldName: "Text Input",
    minLength: 1,
    maxLength: 1000,
    required: false,
    normalizeWhitespace: true,
    sanitizeXSS: true,
    preventInjection: true,
    maxRepeatedChars: 15,
  }
};
